services:
  app:
    container_name: app-server-container
    hostname: app-server
    build:
      context: ..
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ../:/app:cached
    tty: true
    networks:
      - my-blog

networks:
  my-blog:
    external: true
