FROM node:bullseye-slim
WORKDIR /app

RUN apt update \
    && apt-get install -y sudo \
    && apt-get -y install locales \
    && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ Asia/Tokyo
ENV TERM xterm
ENV PYTHONPATH $PYTHONPATH:/app/src
ENV PATH $PATH:/home/vscode/.local/bin
ENV APP_SERVER http://app-server:5000
