services:
  app:
    container_name: web-server-container-finished
    hostname: web-server
    build:
      context: ..
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ../:/app:cached
    tty: true
    networks:
      - my-blog

networks:
  my-blog:
    external: true
